### ISSUE TITLE
use the package for higher ploidy

### ISSUE THREAD

**Issue by Mghanbari43** [AlphaGenes/AlphaPlantImpute2#7]
I get a genotype error when I try to use the "createlib" function on genotypes with dosages out of 0,1,2,9. 
Can the package be used on crops with higher ploidy such as 4x?

**Comment by gregorgorjanc** [comment]
@Mghanbari43 can you share a reproducible example?

All AlphaGenes software is primarily geared towards the diploid setting.

**Comment by Mghanbari43** [comment]
Then the error makes sense because I uses a SNP file of 4n to run the package.
tnx
